### ISSUE TITLE
该程序开发基于什么系统

### ISSUE THREAD

**Issue by caiCoffee** [guanchao/apk_auto_enforce#4]
请问作者该程序开发的时候是在什么系统上面的，是Windows吗，我在linux上运行总是出错。

**Comment by guanchao** [comment]
我是在windows上开发的

cai <notifications@github.com> 于2019年4月16日周二 下午4:43写道：

**Comment by caiCoffee** [comment]
我在linux上运行，我更改了sdk跟ndk的目录，运行的时候报错
[1834271026@login apk_auto_enforce]$ python jiagu.py ./12000102_1.0.7_22410029.apk
[+] Apktool decompiled Target.apk successfully!
[+] Target.apk has no self-defined Application!
[+] Find "String appClassName = ...", replace it with "com.targetapk.MyApplication"
[+] Rebuild TuokeApk project successfully!
[+] Copy smali folder into Target folder...
[+] Modified AndroidManifest.xml...
[+] Apktool recompiled Target successfully!
[+] Rename target app: "Target.modified.apk"
[+] Extracted classes.dex from Target.modifed.apk into TargetApk.zip
Traceback (most recent call last):
  File "jiagu.py", line 271, in <module>
    main()
  File "jiagu.py", line 236, in main
    shutil.copyfile('TuokeApk/app/build/intermediates/transforms/dex/release/folders/1000/1f/main/classes.dex', 'tuoke.dex')
  File "/public/home/1834271026/bin/python2/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'TuokeApk/app/build/intermediates/transforms/dex/release/folders/1000/1f/main/classes.dex'
[1834271026@login apk_auto_enforce]$
所以我想知道这个classes.dex文件（TuokeApk/app/build/intermediates/transforms/dex/release/folders/1000/1f/main/classes.dex）是在程序运行过程中生成的还是原来就有的，我再项目里找不到这个文件

**Comment by yongjiaming** [comment]
> 我在linux上运行，我更改了sdk跟ndk的目录，运行的时候报错
> [1834271026@login apk_auto_enforce]$ python jiagu.py ./12000102_1.0.7_22410029.apk
> [+] Apktool decompiled Target.apk successfully!
> [+] Target.apk has no self-defined Application!
> [+] Find "String appClassName = ...", replace it with "com.targetapk.MyApplication"
> [+] Rebuild TuokeApk project successfully!
> [+] Copy smali folder into Target folder...
> [+] Modified AndroidManifest.xml...
> [+] Apktool recompiled Target successfully!
> [+] Rename target app: "Target.modified.apk"
> [+] Extracted classes.dex from Target.modifed.apk into TargetApk.zip
> Traceback (most recent call last):
> File "jiagu.py", line 271, in 
> main()
> File "jiagu.py", line 236, in main
> shutil.copyfile('TuokeApk/app/build/intermediates/transforms/dex/release/folders/1000/1f/main/classes.dex', 'tuoke.dex')
> File "/public/home/1834271026/bin/python2/lib/python2.7/shutil.py", line 96, in copyfile
> with open(src, 'rb') as fsrc:
> IOError: [Errno 2] No such file or directory: 'TuokeApk/app/build/intermediates/transforms/dex/release/folders/1000/1f/main/classes.dex'
> [1834271026@login apk_auto_enforce]$
> 所以我想知道这个classes.dex文件（TuokeApk/app/build/intermediates/transforms/dex/release/folders/1000/1f/main/classes.dex）是在程序运行过程中生成的还是原来就有的，我再项目里找不到这个文件

需要先运行Tuoke的工程，另外build下的路径需要改成本地编译的路径。

**Comment by traceTenda** [comment]
> 我在linux上运行，我更改了sdk跟ndk的目录，运行的时候报错
> [1834271026@login apk_auto_enforce]$ python jiagu.py ./12000102_1.0.7_22410029.apk
> [+] Apktool decompiled Target.apk successfully!
> [+] Target.apk has no self-defined Application!
> [+] Find "String appClassName = ...", replace it with "com.targetapk.MyApplication"
> [+] Rebuild TuokeApk project successfully!
> [+] Copy smali folder into Target folder...
> [+] Modified AndroidManifest.xml...
> [+] Apktool recompiled Target successfully!
> [+] Rename target app: "Target.modified.apk"
> [+] Extracted classes.dex from Target.modifed.apk into TargetApk.zip
> Traceback (most recent call last):
> File "jiagu.py", line 271, in
> main()
> File "jiagu.py", line 236, in main
> shutil.copyfile('TuokeApk/app/build/intermediates/transforms/dex/release/folders/1000/1f/main/classes.dex', 'tuoke.dex')
> File "/public/home/1834271026/bin/python2/lib/python2.7/shutil.py", line 96, in copyfile
> with open(src, 'rb') as fsrc:
> IOError: [Errno 2] No such file or directory: 'TuokeApk/app/build/intermediates/transforms/dex/release/folders/1000/1f/main/classes.dex'
> [1834271026@login apk_auto_enforce]$
> 所以我想知道这个classes.dex文件（TuokeApk/app/build/intermediates/transforms/dex/release/folders/1000/1f/main/classes.dex）是在程序运行过程中生成的还是原来就有的，我再项目里找不到这个文件

请问你是怎么到这一步的, 我的linux一步一个错
